name: docker-build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Install Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      - name: Setup
        run: |
          docker-compose -v
          docker-compose up -d
          docker image ls
          sleep 10

      - name: Verify
        run: bash .travis/verify.sh

      - name: Clean up 
        run: |
          docker-compose stop
          docker-compose rm -f
